drop extension if exists "pg_net";


  create table "public"."reservations" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "scheduled_date" date not null,
    "scheduled_time" time without time zone not null,
    "client_id" integer,
    "service_description" text,
    "status" text default 'PENDING'::text,
    "user_id" uuid not null default auth.uid()
      );


alter table "public"."reservations" enable row level security;

alter table "public"."clients" add column "user_id" uuid not null default auth.uid();

alter table "public"."clients" alter column "id" add generated by default as identity;

alter table "public"."clients" enable row level security;

alter table "public"."companies" enable row level security;

alter table "public"."employees" add column "user_id" uuid not null default auth.uid();

alter table "public"."employees" alter column "id" add generated by default as identity;

alter table "public"."employees" enable row level security;

alter table "public"."vehicles" add column "user_id" uuid not null default auth.uid();

alter table "public"."vehicles" alter column "id" add generated by default as identity;

alter table "public"."vehicles" enable row level security;

alter table "public"."work_orders" add column "user_id" uuid not null default auth.uid();

alter table "public"."work_orders" alter column "id" add generated by default as identity;

alter table "public"."work_orders" enable row level security;

CREATE UNIQUE INDEX reservations_pkey ON public.reservations USING btree (id);

alter table "public"."reservations" add constraint "reservations_pkey" PRIMARY KEY using index "reservations_pkey";

alter table "public"."clients" add constraint "clients_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."clients" validate constraint "clients_user_id_fkey";

alter table "public"."employees" add constraint "employees_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."employees" validate constraint "employees_user_id_fkey";

alter table "public"."reservations" add constraint "reservations_client_id_fkey" FOREIGN KEY (client_id) REFERENCES public.clients(id) not valid;

alter table "public"."reservations" validate constraint "reservations_client_id_fkey";

alter table "public"."reservations" add constraint "reservations_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."reservations" validate constraint "reservations_user_id_fkey";

alter table "public"."vehicles" add constraint "vehicles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."vehicles" validate constraint "vehicles_user_id_fkey";

alter table "public"."work_orders" add constraint "work_orders_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."work_orders" validate constraint "work_orders_user_id_fkey";

grant delete on table "public"."reservations" to "anon";

grant insert on table "public"."reservations" to "anon";

grant references on table "public"."reservations" to "anon";

grant select on table "public"."reservations" to "anon";

grant trigger on table "public"."reservations" to "anon";

grant truncate on table "public"."reservations" to "anon";

grant update on table "public"."reservations" to "anon";

grant delete on table "public"."reservations" to "authenticated";

grant insert on table "public"."reservations" to "authenticated";

grant references on table "public"."reservations" to "authenticated";

grant select on table "public"."reservations" to "authenticated";

grant trigger on table "public"."reservations" to "authenticated";

grant truncate on table "public"."reservations" to "authenticated";

grant update on table "public"."reservations" to "authenticated";

grant delete on table "public"."reservations" to "service_role";

grant insert on table "public"."reservations" to "service_role";

grant references on table "public"."reservations" to "service_role";

grant select on table "public"."reservations" to "service_role";

grant trigger on table "public"."reservations" to "service_role";

grant truncate on table "public"."reservations" to "service_role";

grant update on table "public"."reservations" to "service_role";


  create policy "Users can insert their own clients"
  on "public"."clients"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "Users can update their own clients"
  on "public"."clients"
  as permissive
  for update
  to public
using ((auth.uid() = user_id));



  create policy "Users can view their own clients"
  on "public"."clients"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Users can insert their own employees"
  on "public"."employees"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "Users can update their own employees"
  on "public"."employees"
  as permissive
  for update
  to public
using ((auth.uid() = user_id));



  create policy "Users can view their own employees"
  on "public"."employees"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Users can insert their own reservations"
  on "public"."reservations"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "Users can update their own reservations"
  on "public"."reservations"
  as permissive
  for update
  to public
using ((auth.uid() = user_id));



  create policy "Users can view their own reservations"
  on "public"."reservations"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Users can insert their own vehicles"
  on "public"."vehicles"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "Users can update their own vehicles"
  on "public"."vehicles"
  as permissive
  for update
  to public
using ((auth.uid() = user_id));



  create policy "Users can view their own vehicles"
  on "public"."vehicles"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Users can insert their own work_orders"
  on "public"."work_orders"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "Users can update their own work_orders"
  on "public"."work_orders"
  as permissive
  for update
  to public
using ((auth.uid() = user_id));



  create policy "Users can view their own work_orders"
  on "public"."work_orders"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



